package com.bnt.enums.lookup;

/**************************
 * @author vaibhav.shejol *
 **************************/

public enum POSEntryMode {
	UNKNOWN,
	MANUAL_OR_KEYED,
	MANGETIC_STRIPE,
	BAR_CODE,
	MSD,
	ICC,
	PAN_AUTOENTRY_CONTACTLESS,
	STORE_AND_FORWARD,
	CONTACTLESS_PAN_MAPPINGSERVICE,
	PAN_ENTRY_VIA_ELECTRONICCOMMERCE,
	PAN_MANUAL_ENTRY_ECOMMERCE,
	PAN_KEYED_CHIPCAPABLE,
	PAN_MAGNETICSTRIPE_CHIPCAPABLE,
	PAN_AUTOENTRY_VIA_SERVER,
	PAN_MANUAL_ENTRY_ECOMMERCE_MAGNETICSTRIPE,
	PAN_AUTO_ENTRY_CONTACTLESS_MAGNETICSTRIPE,
	ICC_CVV_NOT_POSSIBLE,
	PAN_MAPPING_SERVICECONTACTLESS_MAGNETICSTRIPE,
	CARDLESS;
}
