management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.health.db.enabled=false
server.port=${application_liveness_http_port:0}
hsm.url=${hsm_url:http://192.168.101.4:19090/bnt-hsm/v1}
component.transformation.rest.enrichement.mapping.path=${switch.conf.home:conf}/hsm/hsm_lookup_mappings.json