# Application Configuration
spring.application.name=BntSwitchAdminPortalBackend
server.port=${SERVER_PORT:8084}

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.jpa.properties.hibernate.default_schema=${BSWITCH_DB_SCHEMA:bps_switch}
spring.jpa.properties.org.hibernate.envers.default_catalog=${BSWITCH_AUDIT_DB_SCHEMA:bps_switch_audit}
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.hibernate.envers.autoRegisterListeners=true

spring.jpa.properties.org.hibernate.envers.track_entities_changed_in_revision=true
spring.jpa.properties.org.hibernate.envers.audit_table_suffix = _aud
spring.jpa.properties.hibernate.jdbc.time_zone=${date_time_zone:Europe/London}

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#Hibernate batch inserting
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true

#spring.jpa.properties.hibernate.ejb.interceptor=com.bnt.rest.interceptor.CustomEmptyInterceptor

#spring.jpa.hibernate.archive.autodetection=class
spring.data.jpa.repositories.bootstrap-mode=deferred

db.auditing.name=${spring.jpa.properties.org.hibernate.envers.default_catalog} 



#Read+Write DB details
spring.datasource.driverClassName=${DRIVER_NAME:com.mysql.cj.jdbc.Driver}
spring.datasource.url=${JDBC_AWS_VALUE:jdbc:mysql}://${BSWITCH_DB_HOST:172.31.2.75}:${BSWITCH_DB_PORT:3307}/${spring.jpa.properties.hibernate.default_schema}?${JDBC_STRING:allowPublicKeyRetrieval=true&useSSL=${USE_SSL:false}&sslMode=${SSL_MODE:Preferred}&useLegacyDatetimeCode=false&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true}
spring.datasource.username=${BSWITCH_DB_USERNAME:root}
#spring.datasource.pwd=ENC(${BSWITCH_DB_PASSWORD:fXZG9NvphgM5CIBat0VlXlC+BrcyRmU8})
spring.datasource.pwd=${BSWITCH_DB_PASSWORD:root}

#Read Only DB details
spring.datasource.read_url=${JDBC_AWS_VALUE:jdbc:mysql}://${BSWITCH_DB_HOST_READ:172.31.2.75}:${BSWITCH_DB_PORT_READ:3307}/${spring.jpa.properties.hibernate.default_schema}?${JDBC_STRING:allowPublicKeyRetrieval=true&useSSL=${USE_SSL:false}&sslMode=${SSL_MODE:Preferred}&useLegacyDatetimeCode=false&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true}
spring.datasource.read_username=${BSWITCH_DB_USERNAME_READ:root}
#spring.datasource.read_pwd=ENC(${BSWITCH_DB_PASSWORD_READ:fXZG9NvphgM5CIBat0VlXlC+BrcyRmU8})
spring.datasource.read_pwd=${BSWITCH_DB_PASSWORD_READ:root}

#monitoring.service.enabled=false

##Aurora DB
#spring.datasource.driverClassName=${DRIVER_NAME:software.aws.rds.jdbc.mysql.Driver}
#spring.datasource.url=${JDBC_AWS_VALUE:jdbc:mysql:aws}://${BSWITCH_DB_HOST:aurora-cluster-mtwuhwzi.cluster-cz479mxlbl1f.us-east-2.rds.amazonaws.com}:${BSWITCH_DB_PORT:6150}/${spring.jpa.properties.hibernate.default_schema}?${JDBC_STRING:useAwsIam=true&useSsl&serverSslCert=${AWS_PEM_FILE_PATH:I:/Code/HSBC/Aurora/rds-combined-ca-bundle.pem}&autoReconnect=true&connectTimeout=5000}
#spring.datasource.username=${BSWITCH_DB_USERNAME:hsbcswitchAuroraAppAdmin}

#Aurora Audit DB 
#spring.datasource.read_url=${JDBC_AWS_VALUE:jdbc:mysql:aws}://${BSWITCH_DB_HOST_READ:aurora-cluster-mtwuhwzi.cluster-cz479mxlbl1f.us-east-2.rds.amazonaws.com}:${BSWITCH_DB_PORT_READ:6150}/${BSWITCH_DB_SCHEMA:hsbcswitch}?${JDBC_STRING:useAwsIam=true&useSsl&serverSslCert=${AWS_PEM_FILE_PATH:I:/Code/HSBC/Aurora/rds-combined-ca-bundle.pem}&autoReconnect=true&connectTimeout=5000}
#spring.datasource.read_username=${BSWITCH_DB_USERNAME_READ:hsbcswitchAuroraAppAdmin}

jwt.secret=javainuse
session.expiry.time=5

session.multiuser.allow=true

report.max.size=150

spring.mvc.servlet.path=/rest/
spring.jmx.enabled= false
server.max-http-header-size=40KB

server.servlet.context-path=/bntmvpadm
#server.tomcat.accesslog.directory=C:/embedded-tomcat-logs
# Directory in which log files are created. Can be absolute or relative to the Tomcat base dir.
#server.tomcat.accesslog.enabled=true 
#spring.jpa.properties.hibernate.type=trace
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

#spring.jpa.properties.hibernate.ejb.interceptor=com.bnt.rest.interceptor.CustomEmptyInterceptor
#Hikari-pool config
spring.datasource.hikari.connection-timeout=${CONNECTION_TIMEOUT:120000}
spring.jpa.hibernate.id.new_generator_mappings=true
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.hibernate.archive.autodetection=class
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10

spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

spring.velocity.resourceLoaderPath=classpath*:META-INF/velocitytemplates
spring.velocity.prefix=
spring.velocity.suffix=.vm
spring.velocity.cache=false
spring.velocity.check-template-location=true
spring.velocity.content-type=text/html
spring.velocity.charset=UTF-8
spring.velocity.properties.input.encoding=UTF-8
spring.velocity.properties.output.encoding=UTF-8

poll.delay.seconds=30
monitoring.mbeanname=com.bnt.ripps.switch:name=rippsMonitoringServer,type=Monitoring
switch.mbeanname=com.bnt.ripps.switch:type=Switch,name=SwitchVM

# Server Log properties
serverlog.url.base=http://localhost:5601
serverlog.url.log=/app/kibana#/dashboard/RippsAppLog?embed=true&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,columns:!(_source),id:RippsAppLog-records,panelIndex:1,row:1,size_x:12,size_y:7,sort:!('@timestamp',desc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:RippsAppLog,uiState:())



crossOriginUrl=${CROSS_ORIGIN_URL:*}
configbatch.import.temp.location=..//standalone//tmp//
udk.file.dir=..//standalone//adp-udk-acq//udkfile

entity-export.file.dir=export-entity-data
#L1-L3 mapping properties
mapping.file.dir=L1-L3-mapping-files
adpHttpAccept=XML-JSON
adpHttpUms=JSON-GICC
adpIsoGicc=GICC-JSON

adpHttpSms=JSON-JSON
adpIsoSms=ISO-JSON
adpIsoUms=ISO-ISO

app.title=Accept 
app.type=Acquirer

matrix.approved.destinations=VisaVTS,VACP,BaseI,MasterCard,Oracle,EuroNet,PostBridge,Base24eps,UserContainer,MagicNumber,AconiteEMV,Falcon,VodaCom,Base24,Tutuka

matrix.additional.attributes=CardRdngCpblties,CrdhldrVrfctnCpblties,TermnlIntgtn,OnLineCpblties,CardDataNtryMd,MessageType
matrix.dcc.fileprefix=adpIsoSms-AcpCentral
matrix.default.filename=default-mapping.csv
matrix.request.default.filename=DEFAULT-RequestMapping.csv
matrix.response.default.filename=DEFAULT-ResponseMapping.csv

# SSL Configuration
security.require-ssl=false
server.ssl.key-store-type=JKS
server.ssl.key-store=classpath:certificates/keystore.p12
server.ssl.key-store-password=adminportal1234

# Expose over JMX
management.endpoints.jmx.exposure.exclude=shutdown
management.endpoints.jmx.exposure.include=*

# Expose HTTP REST Endpoint
management.endpoints.web.exposure.exclude=
#management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
info.local.server.port=${local.server.port}
info.java.specification.vendor=${java.specification.vendor}
info.java.vm.name=${java.vm.name}
info.java.runtime.version=${java.runtime.version}
info.java.specification.version=${java.specification.version}
info.status=${status}
info.details.db.status=${details.db.status}
entity_list={"entites":[{"id":1,"entityName":"HSMKeyLable"},{"id":2,"entityName":"Country"}]}
request.timeOutType=GlobalTimeOut-HTTP-GIB
request.default.timeOutType=GlobalTimeOut-DEFAULT
global.dumpTimeSpent=true
component.name=bnt-switch-portal
#monitoring.helth.jmx.url=192.168.100.175:8000
#monitoring.helth.jmx.url=${hz_host:172.16.23.17}:${hz_port:8000}
monitoring.helth.jmx.url=

monitoring.health.rest.url=${hz_rest_host:127.0.0.1:9099}
monitoring.component.profile.mapping.rest.url=${hz_loader_rest_url:/component-profile-mapping}
monitoring.health.rest.url.isSSL.enabled=${monitoring_rest_url_isSSLEnabled:false}
monitoring.health.rest.connection.timout.in.seconds=${CONNECTION_WAIT_TIME_SECS:5}

scheduled.reports.file.folder=/home/abdul/scheduled/
release.version=13

locale.default=en_EN,en_EN1,fr_FR
monitoring.core.helth.jmx.url=${hz_host:172.16.23.17}:${hz_port:8000}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.tomcat.max-http-post-size=100MB

jasypt.encryptor.password=portal-mysql-conf
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator


skip.token.url = ${swagger.urls},OPTIONS,generate-token,reset-forgotten-password,reset-password,confirm-token,generate-new-password,login,role-list-user,error,portal-health,meta-info,get-condition-flag,shutdowngracefully,actuator,health,info,metrics,prometheus

#condition screen
string.operator=Equal|equal|value,Like|like|pattern,In|in|value,StartsWith|starts_with|value,RegEx|pattern|pattern,GreaterThan|greaterThan|value,LessThan|lessThan|value,GreaterThanEqual|greaterThanEqual|value,LessThanEqual|lessThanEqual|value,Null|null|value
int.operator=Equal|equal|value,GreaterThan|greaterThan|value,LessThan|lessThan|value,GreaterThanEqual|greaterThanEqual|value,LessThanEqual|lessThanEqual|value
additional.operator=
message.exchange.fields=adapter_id|Adapter,internal_processing_code|IPC,is_saf_processed|IsProcessedBySaf,retry_count|RetryCount
message.context.fields=transaction_type|TransactionType,payment_method|PaymentMethod,internal_processing_code|IPC,transaction_id|TransactionId,synthetic|Synthetic,txn_originator_reference|Region
#iso package excluded field list
iso.packager.fields.exclude=0,1,65
#data files allowed file type list
datafiles.file.allowed.type=.jks

#Keyclaok Configuration
keycloak.url=${KEYCLOAK_URL:http://172.31.2.75:9124}
keycloak.realm=${KEYCLOAK_REALM:BNT}
keycloak.client.id=${KEYCLOAK_CLIENT_ID:BNT-SWITCH}
keycloak.roles=true
keycloak.role.url=${KEYCLOAK_ROLE_API_URL:${keycloak.url}/admin/realms/BNT/roles}
keyclock.role.prefix=${KEYCLOAK_ROLE_PREFIX:BNT-SWITCH}
keycloak.shared.url=${KEYCLOAK_SHARED_URL:${keycloak.url}}
keycloak.ssl.enabled=${KEYCLOAK_OVER_SSL:false}
keycloak.ssl.truststore.path=${KEYCLOAK_TRUSTSTORE_PATH:src/main/resources/certificates/keycloak/truststore.p12}
keycloak.ssl.identity.path=${KEYCLOAK_IDENTITY_PATH:src/main/resources/certificates/keycloak/keystore.p12}
keycloak.ssl.keystore.password=${KEYCLOAK_KEYSTORE_PASSWORD:keycloak1234}
tls.version=${KEYCLOAK_TLS_VERSION:TLSv1.2}
region=${IS_REGION:false}


extractor.ssl.truststore.path=${EXTRACTOR_TRUSTSTORE_PATH:src/main/resources/certificates/extractor/svc.cluster.local.cert.p12}
extractor.ssl.identity.path=${EXTRACTOR_IDENTITY_PATH:src/main/resources/certificates/extractor/svc.cluster.local.cert.p12}
extractor.ssl.keystore.password=${EXTRACTOR_KEYSTORE_PASSWORD:extractor1234}
extractor.tls.version=${EXTRACTOR_TLS_VERSION:TLSv1.2}
extractor.ssl.enabled=${EXTRACTOR_OVER_SSL:false}


ped.url=http://${DH_HOME:127.0.0.1}:${DH_PORT:8090}/handler/pedstatus
ext.url=${EXTRACTOR_URL:http://127.0.0.1:10101/extractor}
ui.code.date=16 March 2026 04:30 PM
mid.mapping.option.list=${MID_MAPPING:acquirer|Acquirer Mapping,merchant|Merchant Chain Mapping,location|Merchant Store Mapping(MID),device|Merchant Terminal Mapping(TID)}
#role for admin portal only view permission
role.viewonly.links=${ROLE_VIEWONLY_LINKS:link_institution,link_merchant,link_location,link_device,link_acquirer}
acquirer.condition.flag=${ACQUIRER_CONDITION_FLAG:true}
functions.optional.parameter.list=${FUNCTIONS_OPTIONAL_PARAMETER:MID_MID_MAPPING,PIN_TRANSLATION}
switch.admin.role=${BSWITCH_ADMIN_ROLE:ADMIN}
bean.tab.hide=${BEAN_TAB_HIDE_FLAG:true}


shutdowndown.gracefully.wait_time=${SHUTDOWN_GRACEFULLY_WAIT_TIME:6000}

spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false

###JMX over SSL client connection properties , used in JmxHelper.java
jmx.ssl.isEnabled=${JMX_SSL_IS_ENABLED:false}
jmx.server.ssl.trustStore.path=${JMX_TRUSTSTORE_PATH:certificates/truststore.ks}
jmx.server.ssl.trustStorePassword=${JMX_TRUSTSTORE_PASSWORD:Apollo13@}

secretNames.endpoint=/secretManager/listSecrets

server.servlet.session.timeout=30s

action.list=VALIDATE_ENTITY_CONFIG,ENRICH_USING_ENTITY_CONFIG
skip.origin.validation=${SKIP_ORIGIN_VALIDATION:false}

secretmanager.enabled=false
dashboard.schedular.time=${DASHBOARD_SCHEDULAR_TIME:60000}

time.interval.gap.for.txnlog= ${TIME_INTERVAL_GAP_FOR_TXNLOG:1}

# Swagger related URLs
swagger.urls = swagger-ui.html,\
				swagger-ui,\
				api-docs,\
				v3/api-docs,\
				index.html,index.css,\
				swagger-resources,\
				swagger-ui-bundle.js,\
				swagger-initializer.js,\
				swagger-ui-standalone-preset.js,\
				swagger-ui.css,\
				swagger-config,\
				favicon-32x32.png,\
				favicon-16x16.png,\
				webjars

# Actuator and Prometheus Configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoint.info.enabled=true
#management.prometheus.metrics.export.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}
management.endpoints.web.base-path=/actuator

# OpenTelemetry Configuration
# reduce to 0.1 (10%) if high traffic in future 
management.tracing.sampling.probability=1.0 
management.otlp.tracing.endpoint=${OTLP_ENDPOINT:http://172.31.2.92:4318/v1/traces}

app.table.names=acquirer_id_config,acquirer_mapping,adapter,adapter_configuration,auth_session,bin_account_transaction_type,bin_account_type,bin_account_type_master,bin_master,bin_table,checker,comment,component_permission,configured_routes,core_property,core_property_detail,country,country_state,currency,custom_bean_configuration,data_files,database_sync_up,delayed_response,deployment,deployment_cluster,deployment_component,deployment_workflow,device,device_model,device_model_configuration,device_type,drool_rule_api,drool_rule_api_detail,drool_rule_parameter,el_expression,encryption_keys,entity_export,ext_etl_job,ext_etl_job_detail,ext_rec_tracker,ext_resend_tracker,ext_send_tracker,function_operation,holiday,imf,imf_template,institution,institution_detail,invalid_message,location,location_detail,lookup_type,lookup_value,menu_function,merchant,merchant_category_code,merchant_code_mapping,merchant_detail,merchant_institution,merchant_institution_detail,merchant_profile,processor_adapter,qrtz_blob_triggers,qrtz_calendars,qrtz_cron_triggers,qrtz_fired_triggers,qrtz_job_details,qrtz_locks,qrtz_paused_trigger_grps,qrtz_scheduler_state,qrtz_simple_triggers,qrtz_simprop_triggers,qrtz_triggers,reversal,routing,routing_version,rule,rule_configuration,rule_input_fields,rule_operator,scheme_imf_mapper,setting,snapshot_export,snapshot_export_detail,snapshot_import_detail,standard_message_specification,sub_menu_function,switch_cluster,synthetic_txn_log,system_bean_configuration,system_role,system_role_function,system_user,system_user_category,system_user_role,tags,transaction_velocity,txn_id_sequence,txn_log,txn_post_processing,ui_txn_label,workflow,workflow_services,DATABASECHANGELOG,DATABASECHANGELOGLOCK,REVINFO
