#Jmx properties

bswitch.type=com.bnt.bswitch:type=Management,name=Instance Manager
bswitch.monitoring.helth=com.bnt.bswitch:type=Management,name=Hazelcast Instance Manager
inflight.count=getInflightCount
isSafe.kill=isSafeToKill
performance.stats=getPerformanceStats
connection.count=getConnectionCount
current.status=getCurrentStatus

jmx.service.uri=service:jmx:rmi:///jndi/rmi://
jmx.rmi=/jmxrmi
stop.consumers=stopConsumers                  
commons.repository=com.bnt.bswitch.db.commons.repository:name=dataSource,type=DBDataSource
log4j.url=org.apache.logging.log4j2:type=512ddf17,component=Loggers,name=com.bnt
log4.level=Level

###Routing Rule JMX #############
workflow.routing_rule.type=com.hazelcast:name=SW-WorkflowRuleConfigMap,instance=_hzInstance_1_Switch-HZ,type=IMap
destination.routing_rule.type=com.hazelcast:name=SW-RoutingRule,instance=_hzInstance_1_Switch-HZ,type=IMap
bswitchLicence.type=com.bnt.bswitch:type=Licence Management,name=BNT Licence
bswitchLicence.method.LicenceDetails=getLicenceExpiry