#Transaction log properties

inflight.transactions=message_collection
msg.exchange=message_exchange
pos.txn.type=transaction_type
pos.payment.method=payment_method
service.type=service_type
adapter.id=adapter_id
## Will reverse their name later in code
internal.processingCode=processing_code
processingStatus=internal_processing_code
msg.route=route
msg.request=request_message
msg.response=response_message
msg.additionalfields=additionalFields
original_data_element=original_data_element

on_us = on_us
rrn=rrn
message_type_indicator=message_type_indicator
transaction_type_indicator=transaction_type_indicator
acquirer_institution_code=acquirer_institution_code
type=type
#####Request Response Path Attributes#####################

safProcessed = is_saf_processed
response.code=response_code









######################################################

txn.amounts=amounts
txn.amount_transaction=amount_transaction
txn.amount_auth_transaction=authorised_amount
txn.balanceRes=balance_response
txn.accountBal=account_balances
txn.balances=balances
txn.name=name
txn.balance=balance
txn.amount=value
txn.currency=currency

auditInfo.createdOn=audit_info.created_on

msg.guid=guid
transaction.date=transaction_date
transaction.response=transaction_response


parent_transaction_id=epp_serial_number
path.transaction_type=$.message_collection[0].message_exchange.request_message.transaction_type_indicator.type
path.masked_card_number=$.message_collection[0].message_exchange.request_message.account_number_masked
path.parent_transaction_id=$.message_collection[0].message_exchange.request_message.epp_serial_number
path.parent_transaction_id.reversal=$.message_collection[0].message_exchange.request_message.rrn
path.advice.parent_transaction_id=$.message_collection[0].message_exchange.request_message.original_data_element.original_message_type_identifier
path.source.acquirer=$.message_collection[0].message_exchange.request_message.acquirer_institution_code
path.advice.parent_advice_staus=$.message_collection[0].message_exchange.request_message.transaction_type_indicator.type
path.destination.acquirer=$.message_collection[1].message_exchange.request_message.acquirer_institution_code
path.amount=$.message_collection[0].message_exchange.request_message.amounts.amount_transaction.value
path.response.code=$.message_collection[0].message_exchange.response_message.response_code
path.saf.processed=$.message_collection[0].message_exchange.is_saf_processed
path.destination.endpoint=$.message_collection[1].message_exchange.route
path.txn.service.type=$.message_collection[1].message_exchange.service_type
path.terminal.id=$.message_collection[0].message_exchange.request_message.terminal_identification
path.message.type=$.message_collection[0].message_exchange.request_message.message_type_indicator.type