export const HeaderInnerConfig = {
  texts: {
    en_EN: {
      HEADER_COUNTRIES: 'Countries',
      HEADER_COUNTRY_STATE: 'Country States',
      HEADER_COUNTRY_ZONE_SCHEME: 'Country Zone Scheme',
      HEADER_CURRENCIES: 'Currencies',
      HEADER_DEVICE_TYPES: 'Device Types',
      HEADER_INSTITUTION_ZONE: 'Institution Zone',
      HEADER_NOTIFICATIONS: 'Notifications',
      HEADER_PROFILE: 'Profile',
      HEADER_SIGNOUT: 'Sign out',
      HEADER_USERS: 'Users',
      HEADER_USER_ROLES: 'User Roles',
      HEADER_VIEW_ALL: 'View all',
      HEADER_VIEW_SETTINGS: 'View Settings',
    },
    en_EN1: {
      HEADER_COUNTRIES: 'Countries',
      HEADER_COUNTRY_STATE: 'Country States',
      HEADER_COUNTRY_ZONE_SCHEME: 'Country Zone Scheme',
      HEADER_CURRENCIES: 'Currencies',
      HEADER_DEVICE_TYPES: 'Device Types',
      HEADER_INSTITUTION_ZONE: 'Institution Zone',
      HEADER_NOTIFICATIONS: 'Notifications',
      HEADER_PROFILE: 'Profile',
      HEADER_SIGNOUT: 'Sign out',
      HEADER_USERS: 'Users',
      HEADER_USER_ROLES: 'User Roles',
      HEADER_VIEW_ALL: 'View all',
      HEADER_VIEW_SETTINGS: 'View Settings',
    },
    fr_FR: {
      HEADER_COUNTRIES: 'Des pays',
      HEADER_COUNTRY_STATE: 'États du pays',
      HEADER_COUNTRY_ZONE_SCHEME: 'Schéma de zone de pays',
      HEADER_CURRENCIES: 'Monnaies',
      HEADER_DEVICE_TYPES: 'Types de périphériques',
      HEADER_INSTITUTION_ZONE: 'Zone institutionnelle',
      HEADER_NOTIFICATIONS: 'Les notifications',
      HEADER_PROFILE: 'Profil',
      HEADER_SIGNOUT: 'Déconnexion',
      HEADER_USERS: 'Utilisateurs',
      HEADER_USER_ROLES: "Rôles d'utilisateur",
      HEADER_VIEW_ALL: 'Voir tout',
      HEADER_VIEW_SETTINGS: "Paramètres d'affichage",
    },
  },
};
