#MEK-DEK Config
#switch.kek=${SWITCH_KEK:a61d0218d2d0a793}
mek.file.location=${SWITCH_HOME:conf}/mekkey.csv
switch.adapter.extended.class=${ADAPTER_EXTENDED_CLASS:com.bswitch.hsbc.Engine}
runtime.property.file.location=${SWITCH_HOME:conf}