#default jdk
hazelcast.logging.type=log4j
hazelcast.multicast=false
hazelcast.tcp=true
#client to connect with server(ip) node
hazelcast.server.ip.list=${HAZELCAST_HOST:127.0.0.1}:${HAZELCAST_PORT:5701}
#max attempt limit 
hazelcast.client.connection.attempt.limit=1000000000
hazelcast.client.connection.attempt.period=10000
hazelcast.client.smart.routing=true
hazelcast.client.redo.operation=true
hazelcast.client.connection.timeout=5000
hazelcast.license.key=ENTERPRISE_HD#10Nodes#rJ0uK7FlNUSfbmyaTHIkA61VOj5wE2898110114010910100190100800111

hazelcast.client.group.name=Switch-HZ
hazelcast.client.group.password=Bnt@123 

#properties section
hazelcast.client.instance.name=swtich-client
hazelcast.client.statistics.enabled=true

hazelcast.client.async-start=false
#OFF, ON or ASYNC
hazelcast.client.reconnect-mode=ON

#near cache config
nearcache.endswith=com.bnt.bswitch.shared.lib.entities.cache.*
nearcache.in-memory-format=OBJECT
nearcache.invalidate-on-change=true
nearcache.eviction-policy=LRU
nearcache.max-size-policy=ENTRY_COUNT
nearcache.size=50000
