sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin123
sonar.projectKey=Bnt-switch
sonar.projectName=Bnt-switch
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
# sonar.projectBaseDir=.
# sonar.sources=src
# sonar.exclusions=**/node_modules/**
# sonar.tests=src
# sonar.test.inclusions=**/status.component.spec.ts,**/deployment-status.component.spec.ts,**/velocity-limits.component.spec.ts,**/acquirer-mapping.service.spec.ts
# sonar.test.inclusions=**/*.spec.ts
# sonar.exclusions=**/node_modules/**
sonar.sources=src
# sonar.exclusions=**/node_modules/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
# sonar.typescript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=reports/sonarqube_report.xml
sonar.coverage.jacoco.xmlReportPaths=reports/ut_report.xml
sonar.scm.disabled=true 
# sonar.exclusions=**/node_modules/**
sonar.exclusions=**/node_modules/**,**/*.css,**/*.scss,**/*.html,**/*.spec.ts,**/assets/**,**/environments/**,**/reports/**,**/karma.conf.js,**/main.ts,**/polyfills.ts,**/test.ts,**/utils.ts,**/*.module.ts,**/tsconfig.json,**/config/**,**/*.conf.ts,**/*Interceptor.ts,
# sonar.exclusions=**/node_modules/**,**/*.css,**/*.scss,**/*.html,**/*.spec.ts,**/assets/**,**/environments/**,**/reports/**,**/karma.conf.js,**/main.ts,**/polyfills.ts,**/test.ts,**/utils.ts,**/*.module.ts,**/tsconfig.json,**/config/**,**/*.effects.ts,**/*.reducers.ts,**/*.reducer.ts,**/*.selector.ts,**/*.selectors.ts,**/*.state.ts,**/*.service.ts,**/*.conf.ts,**/*.action.ts,,**/*.actions.ts,**/*Interceptor.ts,**/*directive.ts,**/*interface.ts
# ,**/*.service.ts
# sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=reports/ut_report.xml