export const en = {
  AND: 'and',
  ACCEPTANCE_BRAND: 'Brand',
  ACCESS_DENIED: 'ACCESS DENIED',
  ACCESS_LOG: 'Access Log',
  ACCESS_POINT: 'Access Point',
  ACCESS_SEARCH_PLACEHOLDER: 'Search by user email',
  ACCOUNT_NAME: 'Account Name',
  ACCOUNT_TYPE_CODE: 'Account Type Code',
  ACCOUNT_TYPE: 'Account Type',
  ACCOUNT_NUMBER: 'Account Number',
  ACCOUNT_NUMBER_REQUIRED: 'Account Number is required',
  ACCOUNT_VALIDATION: 'Please Select Account Number.',
  ACQADAPTERSERVICE: 'Acquirers Adapter Service',
  ACQUIRER: 'Acquirer',
  ACQUIRER_CODE: 'Acquirer Code',
  ACQUIRER_CREATE_ACQUIRER_NAME: 'Acquirer Name',
  ACQUIRER_CREATE_BUTTON: 'Create Institution Acquirer',
  ACQUIRER_ENTITY_CODE: 'Entity Code',
  ACQUIRER_ENTITY_TYPE: 'Entity Type',
  ACQUIRER_ID: 'Acquirer Id',
  ACQUIRER_ID_CONFIG: 'Acquirer',
  ACQUIRER_ID_CONFIG_CREATE: 'Create Acquirer',
  ACQUIRER_ID_CONFIG_DELETE: 'Are you sure you want to delete Acquirer',
  ACQUIRER_ID_CONFIG_EDIT: 'Edit Acquirer',
  ACQUIRER_INSTITUTION_NAME: 'Institution Name',
  ACQUIRER_PROCESSOR: 'Processor',
  ACQUIRER_SEARCH_COMMENT1: 'Type to Filter by Acquirer',
  ACTION: 'Action',
  ACTIONS: 'Actions',
  ACTIVE: 'Active',
  ACTIVATED_ON: 'Scheduled On',
  ACTIVE_SINCE: 'Active Since',
  ACTIVE_TO: 'Active To',
  ADAPTER_CONFIGURATION: 'Adapter Configuration',
  ADD: 'Add',
  ADDRESS: 'Address',
  ADD_CONDITION: 'Add Condition',
  ADD_DEPENDENT_SERVICE: 'Add dependent Service',
  ADD_FIELD: 'Add Field',
  ADD_FUNCTION: 'Add Function',
  ADD_GROUP_SERVICE: 'Add Group Service',
  ADD_MORE_FIELDS: 'Add More Fields',
  ADD_NESTED_FIELD: 'Add Nested Field',
  ADD_NESTED_FIELDS: 'Add Nested Fields',
  ADD_NEW: 'Add New',
  ADD_NEW_SERVICE: 'Add new Service',
  ADD_ONE_WORKFLOW: 'Add one workflow',
  ADD_PARALLEL: 'Add Parallel',
  ADD_PARALLEL_FIELD: 'Add Parallel Field',
  ADD_PARALLEL_FIELDS: 'Add Parallel Fields',
  ADD_SINGLE_FIELD: 'Add Single Field',
  ADD_COMPLEX_FIELD: 'Add Compound Field',
  ADD_XML_ATTRIBUTE: 'Add XML Attribute',
  ADD_REVERSAL_CONDITION: 'Add Reversal Condition',
  ADD_SERVICE: 'Add Service',
  ADD_SERVICES_FOR_REVERSAL: 'Add services for reversal:',
  ADD_SEQUENTIAL: 'Add Sequential',
  ADDITIONAL_ATTRIBUTES: 'Additional Attributes',
  ADITIONAL_SERVICES: 'Additional Services',
  ALERT: 'Alert',
  ALERT_SCREEN: 'Alert Screen',
  ALERT_TYPE: 'Alert Type',
  ALLOWED: 'Allowed',
  ALLZONECODE: 'All Zone Code',
  ALL_ACTION_TYPE: 'All Action Type',
  ALL_ADDRESS: 'All Address',
  ALL_COUNTRIES: 'All Countries',
  ALL_ENTITY_TYPE: 'All Entity Type',
  ALL_INSTITUTION: 'All Institution',
  ALL_INSTITUTION_GROUP: 'All Institution Group',
  ALL_LOCATION: 'All Location',
  ALL_LOGIN_RESULT: 'All Login Result',
  ALL_MERCHANT: 'All Merchant',
  ALL_OBJECTS: 'All Objects',
  ALL_OPTIONS: 'All Options',
  ALL_PROCESSOR: 'All Processor',
  ALL_ROLES: 'All Roles',
  ALL_ROUTING_RULE: 'All Routing Rules',
  ALL_STATUS: 'All Status',
  ALL_TIME: 'All Time',
  ALL_TRANSACTION_LOGS: 'All Transactions Logs',
  ALL_TXN_TYPE: 'All Transaction Type',
  ALL_USER: 'All User',
  ALL_WORKFLOW_GRPOUPS: 'All workflow Groups',
  ALL_WORKFLOW_RULES: 'All Workflows Rules',
  ALL_ZONE: 'All Zones',
  ALLOWED_TRANSACTION: 'Allowed Manual Transactions',
  AUTHENTICATION_METHOD: 'Authentication Methods',
  AMOUNT: 'Amount',
  AMOUNT_VALIDATION: 'Please Enter Numeric Digits Only.',
  ANOTHER_FILE: 'Upload Another File',
  APPLY_LIMIT_TO: 'Apply Limits To',
  APPROVALS: 'Approvals',
  APPROVE: 'Approve',
  APPROVED: 'Approved',
  APPROVED_AMOUNT: 'Approved Amount',
  APP_AMOUNT: 'Approved',
  AREYOUSURE: 'Are You Sure?',
  ASSIGN_VALUE: 'Assign value to internal field',
  ASSIGN_VALUE_TO_RESPONSE_FIELD: 'Assign Value to response field:',
  AUDIT_LOG: 'Audit Log',
  ALIAS: 'Alias',
  ALL_BIN: 'All Bin',
  All_Currencies: 'All Currencies',
  All_Destination: 'All Destination',
  All_Device: 'All Devices',
  ALL_FILES: 'All Files',
  BACK: 'Back',
  BANKING_INFO: 'Banking Info',
  BANK_NAME: 'Bank Name',
  BANK_NAME_REQUIRED: 'Name of bank is required',
  BATCH_MODE: 'Batch Mode',
  Repeat_Time: 'Repeat Time (ms)',
  BIN: 'Bin',
  BIN_ATTRIBUTES: 'Bin Attributes',
  BIN_DATA: 'Bin Data',
  BIN_TABLE: 'Bin Table',
  BIN_DATA_DELETE: 'Are You Sure you want to delete Bin Data Identification No.: ',
  BIN_IDENTIFICATION: 'Identification',
  BIN_RANGE_END: 'Range End',
  BIN_RANGE_START: 'Range Start',
  BRANCH_ADDRESS: 'Branch Address',
  BUDGET_ALLOWED: 'Budget Allowed',
  BUDGET_PERIODS: 'Budget Periods',
  CARTIAGE: 'Cartridge',
  CARTIAGE_ERROR: 'Cartiage is Required.',
  CANCEL: 'Cancel',
  CANCEL_UPLOAD: 'Cancel Upload',
  CARD_OWNER: 'Card Owner',
  CART: 'Cart',
  CATEGORY_CODE: 'Category code',
  CHANGE: 'Change',
  CHECK: 'Check',
  CITY: 'City',
  CLIENT_IP: 'Client IP',
  CLOSE: 'Close',
  CODE: 'Code',
  CODE_ERROR: 'Code is Required.',
  COLUMN_NAME: 'Column Name',
  COMMENT: 'Comment',
  COMMENT1: 'Unable to fetch monitoring data please try again later',
  COMMIT: 'Commit',
  COMM_ADP_ISOGICC: 'COMM ADP ISOGICC',
  COMPONENT_RESPONSE_CODE_FIELD: 'Component Response Code Field',
  CONDITIONAL: 'Conditional',
  CONDITIONAL_WHEN_FOLLOWING_FIELD_PRESENT: 'Conditional when following field present:',
  CONFIGURATION: 'Configuration',
  CONFIRM: 'Confirm',
  CONFIRMDELETE: 'Confirm Delete',
  CONTACTS: 'Contacts',
  CONTACT_INFO: 'Contact Info',
  COPIED: 'Copied!',
  COPY_AS_IS: 'Copy as is',
  CORESYSTEMSERVICE: 'Core System Service',
  COUNT: 'Count',
  COUNTRIES: 'Countries',
  COUNTRIES_ERROR: 'Countries is Required',
  COUNTRIES_ZONE_SCHEME: 'Countries Zone Scheme',
  COUNTRY: 'Country',
  COUNTRYCREATE: 'Country Create',
  COUNTRYNAME: 'Country Name',
  COUNTRY_CODE: 'Country Code',
  COUNTRY_NAME: 'Country Name',
  COUNTRY_NAME_ERROR: 'Country Name is Required.',
  COUNTRY_SEARCH: 'Type to Filter by Country Name',
  CREATE: 'Create',
  CREATE_TAGS: 'Create Tag',
  CREATE_CLUSTER: 'Create Cluster',
  CREATE_L1: 'Create L1 Adapter',
  CREATE_L3: 'Create L3 Adapter',
  CREATED: 'Created',
  CREATEDON: 'Created On',
  CREATED_BY: 'Created By',
  CREATE_ADDRESS1: 'Address Line One',
  CREATE_ADDRESS2: 'Address Line Two',
  CREATE_COMMENT_EMAIL_VALID: 'Please enter a valid email ID',
  CREATE_DESTINATION_ROUTER: 'Create Destination Router',
  CREATE_DEVICE_CODE: 'Create Device Code Mapping',
  CREATE_DEVICE_TYPES: 'Create Device Types',
  CREATE_ERROR_CODE: 'Create Error Code Mapping',
  CREATE_GROUP: 'Create Group',
  CREATE_HSM_KEY: 'Create HSM Key',
  CREATE_JSON: 'Create JSON',
  CREATE_MAGIC_NO: 'Create Magic Number',
  CREATE_NEW_DEPLOYMENT: 'Create New Deployment',
  CREATE_PAYMENT_ROUTER: 'Create Workflow Router',
  CREATE_SNAPSHOT: 'Create Snapshot',
  CREATE_STATE_MACHINE: 'Create State Machine',
  CREATE_TRANSCTION_TYPE: 'Create Transaction Type',
  CREATE_USER: 'Create User',
  CREATE_VELOCITY_LIMIT: 'Create Velocity Limits',
  CREATE_WORKFLOW: 'Create Workflow',
  CURRENCY: 'Currency',
  CURRENCY_CODE: 'Currency Code',
  CURRENCY_ERROR: 'Currency is Required',
  CURRENCY_MINOR_UNIT: 'Currency Minor Unit',
  CURRENCY_MINOR_UNIT_ERROR: 'Currency Minor Unit is Required.',
  CURRENCY_NAME: 'Currency Name',
  CURRENCY_NAME_ERROR: 'Currency Name is Required',
  CURRENCY_SEARCH: 'Type to Filter by Currency',
  CURRENT_SCHEDULE_DEPLOYMENTS: 'Current scheduled deployments',
  CURRENT_VERSION: 'Version',
  CUSTOMCODE: 'Custom Code',
  CUTT_OFF_MAPPING: 'Cut Off Mapping',
  CUT_OFF: 'Cut Off',
  CUT_OFF_CREATE: 'Create Cut Off Mapping',
  CUT_OFF_EDIT: 'Edit Cut Off Mapping',
  CUT_OFF_SELECT: 'Select Cutoff Date & Time',
  CountryStates: 'Country States',
  CountryStatesCreate: 'Create Country States',
  Countryzones: 'Country zones',
  CountryzonesCreate: 'Create Country zones',
  CountryzonesEdit: 'Edit Country zone',
  Currencies: 'Currencies',
  CurrenciesEdit: 'Create Currency',
  DASHBOARD: 'Dashboard',
  DATA_CENTER: 'Data Centre',
  DATA_CENTER_ERROR: 'Data Centre is required.',
  DATA_TYPE: 'Data Type',
  DATE: 'Date',
  DB_DETAIL_LIST: 'DB Information',
  DCC: 'DCC',
  DEFAULT_RESPONSE_CODE: 'Default Response Code',
  DEFAULT_STATE: 'Default State',
  DEFAULT_STATE_ERROR: 'Default State is Rquired',
  DEFAULT_VALUE: 'Default Value',
  DEK: 'Generate DEK',
  RUNTIME_PROPER: 'Runtime Properties',
  DELETE: 'Delete',
  DELETED: 'Deleted',
  DELETE_CONFIRM: 'Are You Sure you want to delete User: ',
  DELETE_CONFIRM1: 'Are You Sure you want to delete Role: ',
  DELETE_CONFIRM2: 'Are You Sure you want to delete Country: ',
  DELETE_CONFIRM_ACQUIRER_CODE: 'Are you sure you want to delete Acquirer Name: ',
  DELETE_CONFIRM_COUNTRY_STATE: 'Are You Sure you want to delete State: ',
  DELETE_CONFIRM_CURRENCY: 'Are You Sure you want to delete Currency: ',
  DELETE_CONFIRM_CUT_OFF: 'Are You Sure you want to delete Cut Off Mapping ID: ',
  DELETE_CONFIRM_DEVICETYPE: 'Do you want to delete Device Type ',
  DELETE_CONFIRM_DEVICE_CODE: 'Are You Sure you want to delete Processor Device Code: ',
  DELETE_CONFIRM_SECURE_CLEANUP:
    'Do you really want to delete Transactions related to this Merchant Group, and the number of Transactions are: ',
  DELETE_CONFIRM_SECURE_CLEANUP_1:
    'You cannot delete Transactions related to this Merchant Group, whose number of Transactions are: ',
  DELETE_CONFIRM_STATE_MACHINE: 'Are You Sure you want to delete Cart : ',
  DELETE_CONFIRM_VELOCITY: 'Are You Sure you want to delete Velocity Limit Transaction Type: ',
  DELETE_COUNTRY_ZONE_CODE: 'Are You Sure you want to delete Zone Code ',
  DELETE_MSG: 'Are you sure you want to delete?',
  DEPENDENT_DATA: 'Dependent Data',
  DEPLOYED_ON: 'Deployed On',
  DEPLOYED_ROUTER: 'Deployed Router',
  DEPLOYED_ROUTER_SCREEN: 'Deployed Router Screen',
  DEPLOYMENT: 'Deployment',
  DEPLOYMENT_HISTORY: 'Deployment History',
  STOP: 'Stop',
  PAUSE: 'Pause',
  JOB_STATUS: 'Job Status',
  DEPLOYMENT_STATUS: 'Deployment Status',
  DESCRIPTION: 'Description',
  DESCRIPTION_DESCRIPTION: 'Please enter role description',
  DESCRIPTION_ERROR: 'Description is Required.',
  DESTINATION: 'Destination',
  DESTINATIONS: 'Destinations',
  DESTINATION_CREATE: 'Create Destination',
  DESTINATION_END_POINT: 'Destination Endpoint',
  DESTINATION_END_POINT_CREATE: 'Create Destination Endpoint',
  DESTINATION_ERROR: 'Destination is Rquired',
  DESTINATION_ROUTER: 'Destination Router',
  DESTINATION_ROUTER_DELETE_COMMENT: 'Are You Sure you want to delete Router: ',
  DESTINATION_ROUTER_EDIT: 'Edit Destination',
  DESTINATION_RULE: 'Destination Rule',
  DESTINATION_VIEW_DETAILS: 'Destination View Details',
  DETAILS: 'Details',
  DEVICE: 'Device',
  DEVICE_ID: 'Device Id',
  DEVICES: 'Devices',
  DEVICE_CODE: 'Device Code:',
  DEVICE_CODE_MAPPING: 'Device Code Mapping',
  DEVICE_CONFIRMDELETE: 'Confirm Delete',
  DEVICE_COUNT: 'Device Count',
  DEVICE_CREATE: 'Create Device',
  DEVICE_DELETE: 'Are you sure you want to delete ',
  DEVICE_IMPORT_LINE:
    'You can import institution groups,institution,locations and devices from CSV file.',
  DEVICE_MODEL_TYPE: 'Device Model Type',
  DEVICE_SEARCH: 'Type to Filter by Name',
  DEVICE_TYPE: 'Device Type',
  DEVICE_TYPE_ERROR: 'Device Type is Required',
  DEVICE_TYPE_LIST_PLACE_HOLDER: 'Please select device type',
  DEVICE_TYPE_MAAPING_LIST_PLACE_HOLDER: 'Please Select Model Type Corrensponding to Device Type',
  DEVICE_TYPE_SEARCH: 'Type to Filter by Code',
  DISABLE: 'Disable',
  DISABLED: 'DISABLED',
  DISABLEDS: 'Disabled',
  DISBALE_DUMPS: 'Disable Dumps',
  DISPENSED_AMOUNT: 'Dispensed Amount',
  DISPLAY_PROMPT: 'Display Prompt',
  DOWNLOAD: 'Download',
  DOWNLOAD_CSV: 'Download Csv',
  DOWNLOAD_FILE_TEMPLATE: 'Download file template',
  DOWNLOAD_PDF: 'Download Pdf',
  DUPLICATE_ENTRY: 'Duplicate Entry',
  DeviceCreate: 'Create Device',
  DeviceDetail: 'Device Details',
  DeviceEdit: 'Edit Device',
  DeviceTypes: 'Device Types',
  Devicestypes: 'Devices types',
  DevicestypesCreate: 'Create Devices type',
  DevicestypesEdit: 'Edit Devices type',
  EDIT: 'Edit',
  EDITPROFILE: 'Edit Profile',
  EDIT_STATE_MACHINE: 'Edit State Machine',
  EL_FUNCTIONS: 'EL Function',
  EL_FUNCTION_CREATE: 'Create EL Function',
  EL_FUNCTION_NAME: 'EL Function Name',
  EMAIL: 'Email',
  EMAIL_IS_REQUIRED: 'Email is required.',
  ENABLE: 'Enable',
  ENABLED: 'ENABLED',
  ENABLEDS: 'Enabled',
  ENABLE_DUMPS: 'Enable Dumps',
  END_TO_END_INTERNAL_RESPONSE_TIME: 'End To End Internal Response Time (ms)',
  ENRICH_FIELDS: 'Enrich Fields:',
  ENRICH_FIELDS_FROM_CONFIGURATION: 'Enrich fields from configuration',
  ENRICH_FIELDS_FROM_CONSTANT_VALUE: 'Enrich fields from constant value',
  ENTER_REQUIRED: 'Enter Required fields*',
  ENTITY: 'Entity',
  ENTITY_ID: 'Entity Id',
  ENTITY_NAME: 'Entity Name',
  ENTITY_VERSION: 'Entity Version',
  ERROR: 'Error',
  ERROR_CODE: 'Error Code',
  ERROR_CODE_MAPPING: 'Error Code Mapping',
  ERROR_CODE_MAPPING_DELETE_COMMENT: 'Are You Sure you want to delete Processor Error Code: ',
  ERROR_MESSAGE: 'Error Message',
  ERROR_TYPE: 'Error Type',
  EVALUATE: 'Evaluate',
  EXCEPTION_QUEUE: 'Exception Queue',
  EXE_TYPE: 'EXE Type',
  EXE_TYPE_REQ: 'EXE Type is Required',
  EXPIRED: 'EXPIRED',
  EXPIRES_IN_DAYS: 'Expires In (Days)',
  EXPIRY_DATE: 'Expiry Date',
  EXPORT: 'Export',
  EXPORTS: 'Exports',
  IMPORT_EXPORT: 'Export/Import',
  EXPRESSION: 'Expression',
  EXPRESSION_REQ: 'Expression is Required.',
  ExportEntities: 'Export Entities',
  EXTRACT_DATA: 'Extract Data',
  FAILED: 'Failed',
  FAILURE: 'Failure',
  FAILURE_REASON: 'Failure Reason',
  FALSE: 'False',
  FAX: 'Fax',
  FEATURE: 'Feature',
  FEATURE_REQ: 'Feature is Required',
  FIELD_ID: 'Field Id',
  FIELD_NAME: 'Field',
  FIELDS_NAMES: 'Field Name',
  FIELD_NAMES: 'Field name',
  FIELD_TYPE: 'Field Type',
  FIELD_VALUE: 'Value',
  FIELD_Z: 'Attach file',
  FILE_ID: 'File ID',
  FILE_NAME: 'File Name',
  FILE_UPLOAD: 'File records has been imported successfully',
  FIRST_NAME: 'First Name',
  FIRST_NAME_ERROR: 'First Name is Required.',
  FOR_REVIEW: 'For Review',
  FORMAT: 'Format',
  FROM_DATE: 'From Date',
  GENERAL_INFO: 'General Info',
  GENERATE_KEY: 'Generate Random Key',
  GENERATE_MEK: 'Generate MEK Component',
  GENERATE_TEXTBOX: 'User Input Key',
  GENERATE_TEXTBOX_ERROR:
    'Please Enter Valid Key.(Minimum 32 Characters with no Special Character)',
  GENERATE_TOKEN: 'Generate Token',
  GENERATE: 'Generate',
  GOTO_DASHBOARD: 'Go to Dashboard',
  GROUP_NAME: 'Group Name',
  GROUP_TYPE: 'Group Type',
  HEALTHCARE_LINK: 'AppLink HealthCheckUp',
  HELP: 'Help',
  HIDE: 'Hide?',
  HIDES: 'Hide',
  HIDDEN: 'Hidden',
  HIDE_RULE: 'Hide Rule',
  HISTORY: 'History',
  HSM_KEYS: 'HSM Keys',
  HSM_KEYS_COUNTER: 'Counter',
  HSM_KEYS_END_DATE: 'End Date',
  HSM_KEYS_INSTITUTION_CODE: 'Institution Code',
  HSM_KEYS_INSTITUTION_GROUP_CODE: 'Institution Group Code',
  HSM_KEYS_KEY_LABEL: 'Key Label',
  HSM_KEYS_KEY_LABEL_ERROR: 'Please Enter Valid Key Label',
  HSM_KEYS_KEY_TYPE: 'Key Type',
  HSM_KEYS_KEY_TYPE_ERROR: 'Please Enter Valid Key Type',
  HSM_KEYS_KEY_VALUE: 'Key Value',
  HSM_KEYS_KEY_VALUE_ERROR: 'Please Enter Valid Key Value',
  HSM_KEYS_KSN: 'KSN',
  HSM_KEYS_SEARCH: 'Type to Filter by Key Type',
  HSM_KEYS_START_DATE: 'Start Date',
  INCOMING_REQUEST: 'Incoming Request',
  ID: 'Id',
  IF_BELOW_CONDITION_MEET: 'If condition meet',
  IFSC_CODE: 'IFSC Code',
  IFSC_CODE_COMMENT: 'Please enter a valid IFSC code. For e.g. QWER012WE3R',
  IFSC_CODE_REQUIRED: 'IFSC Code is required',
  IMF: 'IMF',
  IMF_WITH_ENTITY_FIELD: 'Which field in IMF has Entity field?',
  IMF_VERSION: 'IMF Version',
  IMPORT: 'Import',
  IMPORT_A_FILE: 'Import .XML File',
  IMPORT_EXPORT_PACKAGER: 'Import/Export Packager',
  INACTIVE: 'Inactive',
  INCOMING: 'Incoming',
  INFLIGHT: 'INFLIGHT:',
  INTERNATIONAL: 'International',
  INSTITUTE_COUNT: 'Merchant Institution Count',
  INSTITUTIONS: 'Institutions',
  INSTITUTIONS_GROUP_ERROR: 'Institution Group is Required',
  INSTITUTION_ACQUIRER: 'Institution Acquirer',
  INSTITUTION_ACQUIRER_CREATE: 'Create Institution Acquirer',
  INSTITUTION_ACQUIRER_EDIT: 'Edit Institution Acquirer',
  INSTITUTION_CATEGORY_CODE: 'Institution Category code',
  INSTITUTION_CATEGORY_CODE_COMMENT: 'Please select institution category code',
  INSTITUTION_DELETE: 'Are you sure you want to delete ',
  INSTITUTION_DELETE_COMMA: ' , ',
  INSTITUTION_DELETE_DEVICES: ' devices associated with it?',
  INSTITUTION_DELETE_LOCATIONS: ' locations and ',
  INSTITUTION_DESCRIPTION: 'Institution Description',
  INSTITUTION_ERROR: 'Institution is Required',
  INSTITUTION_GROUP_DELETE: 'Are you sure you want to delete ',
  INSTITUTION_GROUP_DELETE_AND: ' and ',
  INSTITUTION_GROUP_DELETE_DEVICES: ' devices associated with it?',
  INSTITUTION_GROUP_DELETE_INSTITUTIONS: ' institutions, ',
  INSTITUTION_GROUP_DELETE_LOCATIONS: ' locations and ',
  INSTITUTION_GROUP_DESCRIPTION: 'Institution Group Description',
  INSTITUTION_GROUP_ID: 'Institution Group Id',
  INSTITUTION_GROUP_ID_REQUIRED: 'Please select Institution Group Id',
  INSTITUTION_ONLY_REQUIRED: 'Please select Institution',
  INSTITUTION_OPTIONS: 'Institution Options',
  INTEGERATIONFEATURESERVICE: 'Integration Feature Service',
  INTERNAL_CODE: 'Internal Code',
  INTERNAL_MESSAGE_FORMAT: 'Internal Message Format',
  INTERNAL_PROCESSING_CODE: 'Processing Code',
  INTERNAL_PROCESSING_CODE_CREATE: 'Create Processing Code',
  INTERNAL_PROCESSING_CODE_EDIT: 'Edit Processing Code',
  INTERNAL_RESPONSE_TIME: 'Internal Response Time:',
  INTERNATIONAL_CARD_VERIFICATION: 'Internet Card Holder Verification',
  INVALID_LOG: 'Invalid Message Log',
  IN_PROGRESS: 'In Progress',
  ISDCODE: 'ISD Code',
  ISDCODE_ERROR: 'ISD Code is Required ',
  ISOCODE: 'ISO Code',
  ISOCODE_ERROR: 'ISO Code is Required',
  IS_SAFE_TO_KILL: 'IS SAFE TO KILL:',
  IS_SAF_ENABLED: 'Is SAF Enabled',
  InstitutionZone: 'Institution Zone',
  InstitutionZoneCreate: 'Create Institution Zone',
  InstitutionZoneEdit: 'Edit Institution Zone',
  JMX_URL: 'jmxURL:',
  JVM_INFO: 'JVM Information',
  KEY: 'Key',
  KILL: 'Kill',
  L1AdaptersCreate: 'Create L1 Adapters',
  L1AdaptersEdit: 'Edit L1 Adapters',
  L3AdaptersCreate: 'Create L3 Adapters',
  L3AdaptersEdit: 'Edit L3 Adapters',
  L2_JSON: 'L2 Workflow JSON',
  LANGUAGE: 'Language',
  LABEL: 'Label',
  LAST_ATTEMPT_TIME: 'Last Attempt Time',
  LAST_MODIFIED_BY: 'Last Modified By',
  LAST_MODIFIED_ON: 'Last Modified On',
  LAST_NAME: 'Last Name',
  LAST_NAME_ERROR: 'Last Name is Required.',
  LATENCY: 'Latency:',
  LENGTH: 'Length',
  LESS_FILTERS: 'Less Filters',
  LEVEL: 'Level',
  LIMITS: 'Limits',
  LIMIT_AMOUNT: 'Limit Amount',
  LIMIT_COUNT: 'Limit Count',
  LIMIT_TYPE: 'Limit Type',
  LINKED_TRANSACTION_TYPE: 'Linked Transaction Type',
  LIST_VALUES: 'List Values',
  LOCATION: 'Location',
  LOCATION_ID: 'Location Id',
  LOCATIONS: 'Locations',
  LOCATION_ACTIONS: 'Actions',
  LOCATION_COUNT: 'Location Count',
  LOCATION_CREATE: 'Create Location',
  LOCATION_CREATE_DESCRIPTION: 'Location Description',
  LOCATION_CREATE_DESCRIPTION_REQUIRED: 'Location Description is Required',
  LOCATION_CREATE_NAME: 'Location Name',
  LOCATION_CREATE_NAME_IS_REQUIRED: 'Name is required.',
  LOCATION_CREATE_VALID_COUNTRY_IS_REQUIRED: 'Valid Country is required.',
  LOCATION_CREATE_VALID_EMAIL_IS_REQUIRED: 'Valid Email is required.',
  LOCATION_CREATE_VALID_INSTITUTIONGROUP_IS_REQUIRED: 'Valid Institution Group is required.',
  LOCATION_CREATE_VALID_MERCHANT_IS_REQUIRED: 'Valid Merchant is required.',
  LOCATION_CREATE_VALID_STATE_IS_REQUIRED: 'Valid State is required.',
  LOCATION_DELETE: 'Are you sure you want to delete',
  LOCATION_DELETE_AND: ' and ',
  LOCATION_DELETE_COMMENT: 'Do you want to delete this institution?',
  LOCATION_DELETE_DEVICES: ' devices associated with it?',
  LOCATION_DETAIL: 'Location Details',
  LOCATION_EDIT: 'Edit Location',
  LOCATION_ERROR: 'Location is Required',
  LOCATION_IMPORT_COMMENT1:
    'You can import institution groups, institution, locations and devices from CSV file.',
  LOCATION_IMPORT_COMMENT3: 'To replace drop new csv file or',
  LOGGER: 'Logger',
  LOGIN: 'Log In',
  LOGIN_BUTTON: 'Login',
  LOGIN_DATE: 'Login Date',
  LOGIN_RESULT: 'Login Result',
  LOGOUT_DATE: 'Logout Date',
  LOGS: 'Logs',
  LOG_ID: 'Txn ID',
  LOG_USER: 'User',
  LogsDetails: 'Logs Details',
  LookUpType: 'Look Up Type',
  LOOKUP_VALUES: 'Lookup Values',
  CORE_PROPERTIES: 'Core Properties',
  L1_ADAPTERS: 'L1 Adapters',
  L3_ADAPTERS: 'L3 Adapters',
  MAGIC_NO: 'Magic Number',
  MAGIC_SEARCH: 'Type Account Number To Filter Data.',
  MAKE_AS_DEFAULT: 'Make as default',
  MANDATORY: 'Mandatory',
  MAPPER: 'Mapper',
  MAPPING_CREATE: 'Create Merchant Code Mapping',
  MAPPING_MERCHANT_CODE: 'Merchant Code',
  MAPPING_SEARCH_TEXT: 'Search by Processor Name',
  MARKUP_FEE: 'MarkUp Fee',
  MARKUP_FEE_COMMENT: 'MarkUp Fee is required.',
  MARK_REVIEW: 'Mark For Review',
  SCHEDULE_DATE: 'Schedule Date',
  MASTER_CONFIGURATION: 'Master Configuration',
  MASTER_DETAIL: 'Master Detail',
  MAX_TIME_LIMIT_CONFIG: 'Max Time Limit Config',
  MERCHANT: 'Merchant',
  MERCHANT_CODE: 'Merchant',
  MERCHANT_CODE_MAPPING: 'Merchant Code Mapping',
  MERCHANT_CODE_MAPPING_DELETE_COMMENT: 'Are You Sure you want to delete Processor Merchant Code: ',
  MERCHANT_CODE_VALIDATION_PROCESSOR: 'Processor Merchant Code is required ',
  MERCHANT_COUNT: 'Merchant Count',
  MERCHANT_ERROR: 'Merchant is Required',
  MERCHANT_GROUP_CODE: 'Merchant Group Code',
  MERCHANT_NAME: 'Merchant Name',
  MERCHANT_ID: 'Merchant ID',
  MERCHANT_ID_ACQ: 'Merchant Id',
  MERCHANT_INSTITUTION: 'Institution',
  MERCHANT_INSTITUTION_ERROR: 'Institution is required',
  MESSAGE: 'Message',
  MESSAGE_CONTEXT: 'Message Context:',
  MESSAGE_PROTOCAOL: 'Message Protocol Variation',
  MESSAGE_PROTO: 'Message Protocol',
  MESSAGE_STANDARD: 'Message Standard',
  MID_MAPPING: 'MID Mapping',
  MINIMUM_AMMOUNT: 'Minimum Amount',
  MINUTES: 'Minutes',
  MISS_ROUTE: 'Miscellaneous',
  MOD10: 'Mod 10',
  MODEL_NAME: 'Model Name',
  MODIFIED_BY: 'Modified By',
  MODIFY: 'Modify',
  MONITORING: 'Monitoring',
  MONITORING_CORE_DETAIL: 'Monitoring Core JMX Detail',
  MONITORING_HAZELCAST_DETAIL: 'Monitoring Hazelcast JMX Detail',
  MONITORING_SCREEN: 'Monitoring Screen',
  MORE: '',
  MORE_FILTERS: 'More Filters',
  MORE_IMPORT: 'Reset',
  MULTI_DESTINATION: 'Workflow Rule',
  MYPROFILE: 'My Profile',
  NAME: 'Name',
  NAME_ERROR: 'Name is Required.',
  NAME_ERROR_PROCESSING_CODE:
    'Name Should be in Capital Letters(A-Z) and can only have UnderScore(_).',
  NAVIGATION_LEFT_STATUS: 'Status',
  NAVIGATION_LEFT_WORKFLOW_RULE: 'WorkFlow Identification Rule',
  NETWORK: 'Network',
  NETWORK_DUMPS: 'Network Dumps:',
  NETWORK_RESPONSE: 'Network Response',
  NEW_DEPLOYMENT_OR_UPGRADES:
    'New deployment or further upgrades can be done for following components',
  NEW_VALUE: 'New Value',
  NEXT: 'Next',
  NEXT_ATTEMPT_TIME: 'Next Attempt Time',
  NO: 'No',
  NO_APPROVED_RESPONSE_WORKFLOW:
    "If all services don't have approved response, then honor response of below service",
  NOT_ALL_APPROVED: 'In case of failure or not all approved, then always return fix response',
  NOT_ALL_APPROVED_RESPONSE:
    "If all services don't have response as Approved, then consider failed response from below services in given order",
  NODES: 'nodes',
  NOTIFICATION: 'Notification',
  NOTIFICATIONS: 'Notifications',
  NO_DATA: 'No data to display',
  NO_OF_ATTEMPTS: 'No Of Attempts',
  NO_ROUTER_FOUND: 'No Router Found',
  NO_SCHEDULED_DEPLOYMENTS_FOUND: 'No Scheduled Deployments Found.',
  NOT_VERSIONED: 'Not Versioned',
  NO_WORKFLOW_FOUND: 'No Workflow Found.',
  OBJECT: 'Object',
  OLD_VALUE: 'Old Value',
  ONUS: 'Onus',
  ONLY: 'Only',
  ONUS_VALIDATE: 'Onus Validate',
  OPTIONAL: 'Optional',
  OUTGOING: 'Outgoing',
  OUTGOING_RESPONSE: 'Outgoing Response',
  OUTPUT_TYPE: 'Output Type',
  OUTPUT_TYPE_REQ: 'Output Type is Required.',
  OWNER_ICA_ID: 'Owner ICA ID',
  OWNER_ICA_NAME: 'Owner ICA Name',
  PAD: 'Pad',
  PAGINATION: 'Pagination',
  PARAMCOUNT: 'Param Count',
  PARAMCOUNT_REQ: 'Param Count is Required.',
  PARSE_AND_EXTRACT_DATA: 'Parse and Extract Data (if present)',
  PARTIAL_AUTH: 'Partial Auth',
  PATTERN: 'Pattern',
  PAYMENT_METHOD: 'Payment method',
  PAYMENT_METHOD_AQUI: 'Payment Method',
  PAYMENT_METHOD_IS_REQUIRED: 'Payment Method is Required.',
  PED_ID: 'PED ID',
  PED_SERIAL_NO: 'PED Serial No.',
  PED_ADDRESS: 'PED Address',
  PED_STATUS: 'PED Status',
  PER: 'Per',
  PER_5_MINUTES: 'Per 5 Minutes',
  PER_DAY: 'Per Day',
  PER_MONTH: 'Per Month',
  PERSIST: 'Persist?',
  PERSISTS: 'Persist',
  PHONE: 'Phone',
  PHONE_NUMBER: 'Phone Number',
  PHONE_NUMBER_IS_REQUIRED: 'Phone Number is required',
  PLACE_HOLDER_ACTIVE_SINCE: 'Please select active since date',
  PLACE_HOLDER_ACTIVE_TO: 'Please select active to date',
  PLEASE_ADD_ONE_RULE: 'Please add at-least one Condition.',
  PLEASE_ENTER_ACTIVE_SINCE: 'Please correct active since date',
  PLEASE_ENTER_ACTIVE_TO: 'Please correct active to date',
  PLEASE_ENTER_CORRECT_DATE: 'Please select correct date',
  PLEASE_ENTER_DESCRIPTION: 'Please Enter the Description',
  PLEASE_FILL_ALL_FIELDS: 'Please fill all fields.',
  PLEASE_FILL_MENDATORY_FIELDS: 'Please fill all mandatory fields',
  PLEASE_ROUTER_NAME: 'Please Enter the Router Name',
  PLEASE_SELECT_CITY: 'Please Enter City Name.',
  PLEASE_SELECT_COUNTRY: 'Please Select Country',
  PLEASE_SELECT_SERVICE: 'Please Select the service',
  PLEASE_SELECT_STATE: 'Please Select State',
  PLEASE_SELECT_ZIP_CODE: 'Please Enter Valid Zip Code.',
  POSCOUNTRYAFD_AMOUNT: 'PosCountryAFD Amount',
  POS_SAFETY_CHECK: 'POS Safety',
  POST_EXECUTION_ACTIONS: 'Post Execution Actions',
  POST_VALIDATION: 'Post Validation',
  PREVIOUS: 'Previous',
  PRIORTY: 'Priority',
  PROCESSOR: 'Processor',
  PROCESSOR_ADAPTER: 'Processor Adapter',
  PROCESSOR_ADAPTER_CREATE: 'Create Processor Adapter',
  PROCESSOR_ADAPTOR: 'Processor Adapter',
  PROCESSOR_CONFIG: 'Processor Config',
  PROCESSOR_DEVICE_CODE: 'Processor Device Code',
  PROCESSOR_ERROR_CODE: 'Processor Error Code',
  PROCESSOR_ID: 'Processor Id',
  PROCESSOR_MERCHANT_CODE: 'Processor Merchant Code',
  PROCESSOR_NAME: 'Processor Name',
  PRODUCT: 'Brand Product',
  PRODUCT_TYPE: 'Product Type',
  PROFILE: 'Profile',
  PROJECTOR_VIEW: 'Projector View',
  PROPERTY_NAME: 'Property Name',
  PROPERTY_VALUE: 'Property Value',
  PUBLISH: 'Publish',
  QUEUE: 'QUEUE:',
  REFRESH_TIME: 'Refresh Time',
  REFUND_OFFLINE: 'Refund Offline',
  REGION: 'Region',
  REGION_ERROR: 'Region is required.',
  REJECT: 'Reject',
  REMOVE_THIS_FIELD: 'Remove this Field',
  BNT_ADMIN: 'Bnt Admin',
  REPORTS: 'Reports',
  REQUEST: 'Request',
  REQUEST_DATE_TIME: 'Request Date Time',
  REQUEST_INITIATOR: 'Request Initiator',
  REQUEST_MAPPING_FROM_MESSAGE: 'Request Mapping From Message',
  REQUEST_MATRIX: 'Request Matrix',
  REQUEST_TYPE: 'Request Type',
  REQUIRED_ADDRESS: 'Address is required',
  REQUIRED_PHONE_NUMBER: 'Phone Numer is required',
  REQ_AMOUNT: 'Requested',
  RESET: 'Reset',
  RESET_FILTERS: 'Reset Filters',
  RESPONSE: 'Response',
  RESPONSE_CODE: 'Response Code',
  RESPONSE_CODE_DECISION: 'Response Code Decision',
  RESPONSE_CODE_DESCRIPTION: 'Response Code Description',
  RESPONSE_DATA_TIME: 'Response Date Time',
  RESPONSE_MAPPING_FROM_MESSAGE: 'Response Mapping From Message',
  RESPONSE_MATRIX: 'Response Matrix',
  RESPONSE_RULE: 'Response Rule',
  RESUME: 'Resume',
  START: 'Start',
  REVISION_ID: 'Revision Id',
  REVERSAL_CONDITION: 'Reversal Condition',
  REVERSAL_TIMEOUT: 'Reversal Timeout',
  REVERT_ALL_CHANGES: 'Revert All Changes',
  ROLEFUNCTIONS: 'Role Functions',
  ROLE_ERROR: 'Role is Required',
  ROLE_NAME: 'Role Name',
  ROLE_NAME_ERROR: 'Role Name is Required.',
  ROLE_FUNCTION_ERROR: 'Function is Required.',
  ROUTER: 'Workflow Router',
  ROUTER_DESCRIPTION: 'Router Description',
  ROUTER_EDIT: 'Edit Router',
  ROUTER_NAME: 'Router Name',
  ROUTER_RULE_DETAILS: 'Router Rule Details',
  ROUTER_TYPE: 'Router Type',
  ROUTING: 'Routing',
  ROUTING_RULE: 'Routing Rule',
  ROW_NO: 'Row no',
  RULE: 'Rule',
  RULES: 'Rules',
  RULE_DESCRIPTION: 'Rule Description',
  RULE_INFO: 'Rule Info',
  RULE_JSON: 'Rule JSON',
  RULE_NAME: 'Rule Name',
  RuleEngineRoute: 'Rule Engine(Route)',
  Rule_Engine_Workflow: 'Rule Engine Workflow',
  SAF: 'SAF',
  SAF_QUEUE: 'SAF Queue',
  SAVE: 'Save',
  SAVE_AS_NEW: 'Save as a new Version',
  SAVE_DRAFT: 'Save Draft',
  SCHEDULE_ON: 'Schedule On',
  SCHEDULE_ROUTER: 'Schedule Router',
  SCHEDULE_ROUTER_DEPLOYED_ON: 'Deployed On',
  SCHEDULE_ROUTER_ROUTE: 'Route',
  SCHEDULE_ROUTER_ROUTER: 'Router',
  SCHEDULE_ROUTER_SCHEDULE_ON: 'Schedule On',
  SCHEDULED_ON: 'Scheduled On',
  SCHEDULE_SELECT: 'Select',
  SCHEDULE_ROUTER_SERVICE_TYPE: 'Service Type',
  SCHEDULE_ROUTER_VERSION_DEPLOYMENT: 'Schedule Router Version Deployment',
  SCHEDULE_SELECT_DATE: 'Select Date',
  SCHEDULE_SELECT_ROUTER: 'Select Router',
  SCHEDULE_SELECT_VERSION: 'Select Version',
  SCHEME: 'Scheme',
  SCHEMES: 'Schemes',
  SCHEME_ERROR: 'Schemes is Required',
  SCHEME_NAME: 'Scheme Name',
  SCRIPT: 'Script',
  SEARCH: 'Search',
  SEARCH_BAR: 'Type to Filter by User Role',
  SEARCH_BY_PROCESSOR: 'Search By Processor Name',
  SEARCH_COUNTRYZONE: 'Search Country Zone By Scheme',
  SECURE_CLEANUP: 'Secure Clean Up',
  SELECT_ACQUIRER_NAME: 'Please select Acquirer Name',
  SELECT_ALL: 'Select all',
  SELECT_CARTIAGE: 'Select Cartridge',
  SELECT_FIELDS: 'Select fields',
  SELECT_FUNCTIONS: 'Select Functions',
  SELECT_INSITITION: 'Please select Institution',
  SELECT_INSITITION_GROUP: 'Please select Institution Group',
  SELECT_INSTITUTION_NAME: 'Please select Institution Name',
  SELECT_LOCATION: 'Please select Location',
  SELECT_OBJECT: 'Select Object',
  SELECT_OPERATOR: 'Select operator',
  SELECT_PROCESSOR: 'Select Processor',
  SELECT_PROCESSOR_NAME: 'Please select Processor Name',
  SELECT_SERVICE: 'Select Service',
  SELECT_SCHEME: 'Select Scheme',
  SELECT_STATUS: 'Select Status',
  SEND_TOKEN: 'Send Token',
  SENSITIVE: 'Sensitive?',
  SENSITIVES: 'Sensitive',
  SERVICEE: 'Service:',
  SERCICE_TYPE: 'Services Type',
  SERVER_ERROR: 'Server Error',
  SERVER_PORT: 'Server Port',
  SERVICE: 'Service',
  SERVICES: 'Services',
  SERVICE_CODE: 'Service Code',
  SERVICE_CREATE: 'Create Service',
  SERVICES_ERROR: 'Services is Required.',
  SESSION_ID: 'Session ID',
  SET_IPC: 'Set IPC',
  SET_CONSTANT_VALUE: 'Set constant values to internal fields (Enrich message)',
  SETUP: 'Setup',
  SHORTCODE: 'Short Code',
  SHORTCODE_ERROR: 'Short Code is Required',
  SHOW_DEVICES: 'Show Devices',
  SHOW_RULE: 'Show Rule',
  SIGNOUT: 'Sign out',
  SINGLE_TRANSACTION: 'Single Transaction',
  SORRY_FOR_INCONVENIENCE: 'Sorry for inconvenience, we are working on fixing the problem',
  SPECIFICATION_RESPONSE_CODE_MAPPING: 'Specification response code mappings',
  STATE: 'State',
  STATE_FLOW: 'State Flow',
  STATE_FLOW_ERROR: 'Flow is Required',
  STATE_MACHINE: 'State Machine',
  STATE_NAME: 'State Name',
  STATE_NAME_ERROR: 'State Name is Required.',
  STATE_SEARCH: 'Type to Filter by State Name',
  STATUS: 'Status',
  STEPS: 'Steps',
  SUBMIT: 'Submit',
  SUB_TYPE: 'Sub Type',
  SUB_TYPE_SELECT: 'Sub Type',
  SUCCEEDED: 'Succeeded',
  SUSPEND: 'Suspend',
  SWAGGER_LINK: 'Swagger Link Url',
  SWITCH_CLUSTERS: 'Cluster',
  SWITCH_CLUSTERS_CREATE: 'Create Cluster',
  SWITCH_CLUSTERS_EDIT: 'Edit Cluster',
  SWITCH_PORTAL_HEALTH: 'Switch Portal Health',
  TABLE_NAME: 'Table Name',
  TEMPLATE: 'Template',
  TEMPLATE_LIST: 'Template List',
  TERMINAL_ID: 'Terminal ID',
  TESTING_FOR_TOOLTIP_POSITION: 'Testing this for tooltip position.',
  THEN_APPLY_BELOW: 'then apply below',
  TID_MAPPING: 'TID Mapping',
  TIME_1_Hour: '1 Hour',
  TIME_24_Hour: '24 Hours',
  TIME_2_Hour: '2 Hours',
  TIME_30_MIN: '30 Minutes',
  TITLE: 'Login',
  TOKEN: 'Token',
  TO_DATE: 'To Date',
  TPS: 'TPS',
  TRANSACTION: 'Transaction',
  TRANSACTIONS_COUNT: 'Transactions Count',
  TRANSACTION_AMOUNT: 'Transaction Amount',
  TRANSACTION_CURRENCY: 'Transaction Currency',
  TRANSACTION_DATE: 'Transaction Date',
  TRANSACTION_ID: 'Transaction ID',
  TRANSACTION_LOG: 'Transaction Log',
  TRANSACTION_LOG_SEARCH_COMMENT1: 'Type to filter transaction id',
  TRANSACTION_RESPONSE: 'Transaction Response',
  TRANSACTION_STATUS: 'Transaction Status',
  TRANSACTION_TYPE: 'Transaction Type',
  TRANSACTION_TYPES: 'Transaction Types',
  TRANSACTION_TYPE_CREATE: 'Create Transaction Type',
  TRANSACTION_TYPE_EDIT: 'Edit Transaction Type',
  TRANSMISSION_PROTOCOL: 'Transmission Protocol',
  TRUE: 'True',
  TXN_DEVICE_CODE: 'Device Code',
  TXN_GUID: 'Txn GuID',
  TXN_LOCATION_CODE: 'Location Code',
  TXN_MERCHANT_CODE: 'Merchant Code',
  TXN_NAME: 'Txn Name',
  TYPE: 'Type',
  TYPE_CODE: 'Type Code',
  TYPES: 'Type:',
  TYPE_ERROR: 'Type is Required',
  UNMARK_REVIEW: 'Unmark For Review',
  UNPDEPLOYV: 'Undeploy',
  UNREACHABLE_SINCE: 'UNREACHABLE SINCE:',
  UNSELECT_ALL: 'Unselect all',
  UPDATE: 'Update',
  UPDATED: 'Updated',
  UPDATED_BY: 'updated by',
  UPDATED_ON: 'Updated On',
  UPLOADED_ON: 'Uploaded On',
  UPLOADING: 'Uploading',
  UP_SINCE: 'UP SINCE:',
  USER: 'User',
  USERNAME: 'User Name',
  USERROLE: 'User Role',
  USER_INFO: 'User Info',
  USER_NAME: 'User Name',
  USER_ROLE: 'Role',
  USER_ROLE_FUNCTIONS: 'User Role Functions',
  USER_ROLE_ID: 'User / Role Details',
  USER_SEARCH: 'Type to Filter by User Name',
  UserCreate: 'Create User',
  UserEdit: 'Edit User',
  RoleMapping: 'Create Role mapping',
  UserRoleEdit: 'Edit User Role',
  UserRoles: 'Role Mapping',
  UserRoles1: 'Role Mapping',
  Users: 'Users',
  VALID: 'Valid',
  VALIDATE: 'Validate',
  VALIDATION_ACQUIRER_CODE: 'Acquire Code is required',
  VALIDATION_DEVICECODE: 'Device Code is required.',
  VALIDATION_ERROR_CODE: 'Error Code is required',
  VALIDATION_ERROR_TYPE: 'Error Type is required',
  VALIDATION_MERCHANTCODE: 'Merchant Code is required.',
  VALIDATION_NUMBER: 'Please Select a Valid Number',
  VALIDATION_PROCESSOR: 'Processor Error Code is required.',
  VALIDATION_PROCESSOR_DEVICECODE: 'Processor Device Code is required.',
  VALIDATION_PROCESSOR_ID: 'Processor Id is required ',
  VALIDATION_PROCESSOR_NAME: 'Processor Name is required.',
  VALID_PHONE_NUMBER: 'Phone Numer is invalid',
  VALUE: 'Value',
  VELOCITY: 'Velocity',
  VELOCITY_CREATE: 'Create Velocity Limit',
  VELOCITY_EDIT: 'Edit Velocity Limit',
  VELOCITY_LIMIT: 'Velocity Limits',
  VELOCITY_LIMITS_LABELS: ' ',
  VELOCITY_LIMIT_DETAILS: 'Velocity Limits Details',
  VELOCITY_SEARCH: 'Search by Apply Limit To',
  VERIFY: 'Verify',
  VERSION: 'Version',
  VERSION1: 'Latest Code Updated Date',
  VERSION_DEPLOYED: 'Version Deployed',
  VIEW: 'View',
  VIEWDETAILS: 'View Details',
  VIEW_ALL: 'View all',
  VIEW_ATTRIBUTES: 'View Attributes',
  VIEW_DETAILS: 'View Details',
  VIEW_JSON: 'View JSON',
  VIEW_ON_LIST: 'List',
  VIEW_ON_MAP: 'Map',
  VIEW_RULE: 'View Rule',
  ViewSettings: 'View Settings',
  VIEW_EMV_DATA: 'View EMV Data',
  WORKFLOW: 'Workflow',
  WORKFLOWS: 'WorkFlows',
  WORKFLOW_JSON: 'Workflow JSON',
  WORKFLOWS_ROUTER: 'Workflow Router',
  WORKFLOW_ADD: 'Add Workflow',
  WORKFLOW_COMMENT1: 'Workflow Groups for all the payment methods already created',
  WORKFLOW_COMMENT2: 'Payment Method is',
  WORKFLOW_GROUP: 'Workflow Group',
  WORKFLOW_GROUP_CREATE: 'Create Workflow Group',
  WORKFLOW_GROUP_DELETE: 'Delete Group',
  WORKFLOW_GROUP_PAYMENTS: 'Group Payment Methods',
  WORKFLOW_NAME: 'Workflow Id',
  WORKFLOW_OPTIONS: 'Work?ow Options',
  WORKFLOW_ROUTER: 'Workflow Router',
  WORKFLOW_RULES: 'Workflow Rules',
  WORKFLOW_ROUTER_EDIT: 'Edit Workflow Router',
  WORKFLOW_SELECT_ADDRESS: 'All Modes of Payments',
  WORKFLOW_SERVICES: 'Workflow Services',
  WORKFLOW_SERVICES_ADD: 'Add Services',
  WORKFLOW_VIEW_DETAILS: 'Workflow View Details',
  YES: 'Yes',
  YES_DELETE: 'Yes, Delete !',
  YOU_HAVE: 'You have',
  ZIP_CODE: 'Zip Code',
  ZONE: 'Zone',
  ZONECODE: 'Zone Code',
  ZONECODES: 'Zone Codes',
  ZONECODES_ERROR: 'Zone Codes is Required',
  ZONE_ERROR: 'Zone is Required',
  MERCHANT_REPORTS: 'Merchant Reports',
  ROUTE: 'Route',
  SEARCH_PED_ID: 'Search by PED ID',
  RELOAD_EMV: 'Reload EMV',
  STORE: 'Store',
  PED: 'PED',
  SELECT_ENTITY: 'Select Entity',
  TXNKEYLABLE: 'Transaction Key Lable',
  TXNKEYLABLECREATE: 'Transaction Key Lable Create',
  TXNKEYLABLEEDIT: 'Transaction Key Lable Edit',
};
